name: Python Dependency Installation
  uses: py-actions/py-dependency-install@v3.0.0

steps:
  # this Action should follow steps to set up Python build environment
  - name: Install Python dependencies
    uses: py-actions/py-dependency-install@v3
    with:
      path: "path/to/requirements.txt"
    with:
      update-pip: "false"
      update-setuptools: "false"
      update-wheel: "false"
